cmake_minimum_required(VERSION 3.0)

if (NOT DEFINED GLM_DIR)
  set(GLM_DIR ${PROJECT_SOURCE_DIR}/3rd/glm)
endif()

if (EXISTS ${GLM_DIR})
  message(STATUS "glm find: ${GLM_DIR}")
  if (NOT TARGET glm)
    add_subdirectory(${GLM_DIR})
  endif()
  set(glm_FOUND TRUE)
else()
  message(WARNING "glm not found! please set {GLM_DIR} correctly!")
  set(glm_FOUND FALSE)
endif()
