include_guard()
option(varC  "fucking option" ON)
if (NOT DEFINED varA)
  set(varA "")
endif()
if (NOT DEFINED varB)
  set(varB "v${varA}")
endif()
if (varC)
  message(STATUS "ONNNNNNNN")
  message(STATUS "${varA} and ${varB} and ${varC}")
else()
  message(STATUS "OFFFF")
  message(STATUS "${varA} and ${varB} and ${varC}")
endif()
