cmake_minimum_required(VERSION 3.0)
if (NOT DEFINED CMDLINE_DIR)
  set(CMDLINE_DIR ${PROJECT_SOURCE_DIR}/3rd/cmdline)
endif()

if (EXISTS ${CMDLINE_DIR})
  message(STATUS "cmdline find: ${CMDLINE_DIR}")
  if (NOT TARGET cmdline)
    add_library(cmdline INTERFACE)
    target_include_directories(cmdline INTERFACE ${CMDLINE_DIR})
  endif()
  set(cmdline_FOUND TRUE)
else()
  message(WARNING "cmdline not found! please set {CMDLINE_DIR} correctly!")
  set(cmdline_FOUND FALSE)
endif()
