if (NOT DEFINED LBFGSPP_DIR)
  set(LBFGSPP_DIR ${PROJECT_SOURCE_DIR}/3rd/LBFGSpp)
endif()

if (EXISTS ${LBFGSPP_DIR})
  message(STATUS "LBFGSpp find: ${LBFGSPP_DIR}")
  if (NOT TARGET LBFGSpp)
    add_library(LBFGSpp INTERFACE)
    target_include_directories(LBFGSpp INTERFACE ${LBFGSPP_DIR}/include)
  endif()
  set(LBFGSpp_FOUND TRUE)
else()
  message(WARNING "LBFGSpp not found! please set {LBFGSPP_DIR} correctly!")
  set(LBFGSpp_FOUND FALSE)
endif()
