if (NOT DEFINED VISIT_STRUCT_DIR)
  set(VISIT_STRUCT_DIR ${PROJECT_SOURCE_DIR}/3rd/visit_struct)
endif()

if (EXISTS ${VISIT_STRUCT_DIR}/include)
  message(STATUS "visit_struct find: ${VISIT_STRUCT_DIR}")
  if (NOT TARGET visit_struct)
    add_library(visit_struct INTERFACE)
    target_include_directories(visit_struct INTERFACE ${VISIT_STRUCT_DIR}/include)
  endif()
  set(visit_struct_FOUND TRUE)
else()
  message(WARNING "visit_struct not found! please set {VISIT_STRUCT_DIR} correctly!")
  set(visit_struct_FOUND FALSE)
endif()
